on:
  push:
    branches:
      - stable

permissions:
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up git (GH actions fail without)
        run: |
          git config --global user.name "I am a bot"
          git config --global user.email "noOneReadsThis@users.noreply.github.com"
      - name: Merge stable into main
        run: |
          git checkout main
          git merge --no-ff stable
      - name: Create new branch and push
        run: |
          git checkout -b new-branch main
          git push origin new-branch
      - name: pull-request
        run: |
          gh_pr_up() { gh pr create $* || gh pr edit $* }
          gh_pr_up --title "My pull request" --body "Description"

